<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SmartParking.Application\SmartParking.Application.csproj" />
		<ProjectReference Include="..\SmartParking.Domain\SmartParking.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="11.1.0" />
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Microsoft.ML" Version="5.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
		<PackageReference Include="FirebaseAdmin" Version="3.6.0" />
		<PackageReference Include="Iyzipay" Version="2.1.78" />
		<PackageReference Include="MongoDB.Driver" Version="3.11.2" />
	</ItemGroup>
</Project>
